name: CD

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
  build-and-deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: de-vri-es/setup-git-credentials@v2
        with:
          credentials: ${{ secrets.GIT_CREDENTIALS }}

      - name: Git setup
        run: |
          git config --global user.email "mateuseap@mateuseap.com"
          git config --global user.name "Mateus Elias"

      - name: Build & Deploy
        working-directory: frontend
        run: |
          npm install
          npm run build
          npm run deploy
